/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MyTicketsRouteImport } from './routes/my-tickets'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HostsSlugRouteImport } from './routes/hosts.$slug'
import { Route as HostNewRouteImport } from './routes/host.new'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as HostSlugReportsRouteImport } from './routes/host.$slug.reports'
import { Route as HostSlugMembersRouteImport } from './routes/host.$slug.members'
import { Route as HostSlugDashboardRouteImport } from './routes/host.$slug.dashboard'
import { Route as HostSlugEventsNewRouteImport } from './routes/host.$slug.events.new'
import { Route as HostSlugEventsEventIdGalleryRouteImport } from './routes/host.$slug.events.$eventId.gallery'
import { Route as HostSlugEventsEventIdEditRouteImport } from './routes/host.$slug.events.$eventId.edit'
import { Route as HostSlugEventsEventIdCheckInRouteImport } from './routes/host.$slug.events.$eventId.check-in'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketsRoute = MyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsSlugRoute = HostsSlugRouteImport.update({
  id: '/hosts/$slug',
  path: '/hosts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HostNewRoute = HostNewRouteImport.update({
  id: '/host/new',
  path: '/host/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugReportsRoute = HostSlugReportsRouteImport.update({
  id: '/host/$slug/reports',
  path: '/host/$slug/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugMembersRoute = HostSlugMembersRouteImport.update({
  id: '/host/$slug/members',
  path: '/host/$slug/members',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugDashboardRoute = HostSlugDashboardRouteImport.update({
  id: '/host/$slug/dashboard',
  path: '/host/$slug/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugEventsNewRoute = HostSlugEventsNewRouteImport.update({
  id: '/host/$slug/events/new',
  path: '/host/$slug/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSlugEventsEventIdGalleryRoute =
  HostSlugEventsEventIdGalleryRouteImport.update({
    id: '/host/$slug/events/$eventId/gallery',
    path: '/host/$slug/events/$eventId/gallery',
    getParentRoute: () => rootRouteImport,
  } as any)
const HostSlugEventsEventIdEditRoute =
  HostSlugEventsEventIdEditRouteImport.update({
    id: '/host/$slug/events/$eventId/edit',
    path: '/host/$slug/events/$eventId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const HostSlugEventsEventIdCheckInRoute =
  HostSlugEventsEventIdCheckInRouteImport.update({
    id: '/host/$slug/events/$eventId/check-in',
    path: '/host/$slug/events/$eventId/check-in',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/my-tickets': typeof MyTicketsRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/host/new': typeof HostNewRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host/$slug/dashboard': typeof HostSlugDashboardRoute
  '/host/$slug/members': typeof HostSlugMembersRoute
  '/host/$slug/reports': typeof HostSlugReportsRoute
  '/host/$slug/events/new': typeof HostSlugEventsNewRoute
  '/host/$slug/events/$eventId/check-in': typeof HostSlugEventsEventIdCheckInRoute
  '/host/$slug/events/$eventId/edit': typeof HostSlugEventsEventIdEditRoute
  '/host/$slug/events/$eventId/gallery': typeof HostSlugEventsEventIdGalleryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/my-tickets': typeof MyTicketsRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/host/new': typeof HostNewRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host/$slug/dashboard': typeof HostSlugDashboardRoute
  '/host/$slug/members': typeof HostSlugMembersRoute
  '/host/$slug/reports': typeof HostSlugReportsRoute
  '/host/$slug/events/new': typeof HostSlugEventsNewRoute
  '/host/$slug/events/$eventId/check-in': typeof HostSlugEventsEventIdCheckInRoute
  '/host/$slug/events/$eventId/edit': typeof HostSlugEventsEventIdEditRoute
  '/host/$slug/events/$eventId/gallery': typeof HostSlugEventsEventIdGalleryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/my-events': typeof MyEventsRoute
  '/my-tickets': typeof MyTicketsRoute
  '/privacy': typeof PrivacyRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/events/$slug': typeof EventsSlugRoute
  '/host/new': typeof HostNewRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/host/$slug/dashboard': typeof HostSlugDashboardRoute
  '/host/$slug/members': typeof HostSlugMembersRoute
  '/host/$slug/reports': typeof HostSlugReportsRoute
  '/host/$slug/events/new': typeof HostSlugEventsNewRoute
  '/host/$slug/events/$eventId/check-in': typeof HostSlugEventsEventIdCheckInRoute
  '/host/$slug/events/$eventId/edit': typeof HostSlugEventsEventIdEditRoute
  '/host/$slug/events/$eventId/gallery': typeof HostSlugEventsEventIdGalleryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/explore'
    | '/my-events'
    | '/my-tickets'
    | '/privacy'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/events/$slug'
    | '/host/new'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/host/$slug/dashboard'
    | '/host/$slug/members'
    | '/host/$slug/reports'
    | '/host/$slug/events/new'
    | '/host/$slug/events/$eventId/check-in'
    | '/host/$slug/events/$eventId/edit'
    | '/host/$slug/events/$eventId/gallery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/explore'
    | '/my-events'
    | '/my-tickets'
    | '/privacy'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/events/$slug'
    | '/host/new'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/host/$slug/dashboard'
    | '/host/$slug/members'
    | '/host/$slug/reports'
    | '/host/$slug/events/new'
    | '/host/$slug/events/$eventId/check-in'
    | '/host/$slug/events/$eventId/edit'
    | '/host/$slug/events/$eventId/gallery'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/explore'
    | '/my-events'
    | '/my-tickets'
    | '/privacy'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/events/$slug'
    | '/host/new'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/host/$slug/dashboard'
    | '/host/$slug/members'
    | '/host/$slug/reports'
    | '/host/$slug/events/new'
    | '/host/$slug/events/$eventId/check-in'
    | '/host/$slug/events/$eventId/edit'
    | '/host/$slug/events/$eventId/gallery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExploreRoute: typeof ExploreRoute
  MyEventsRoute: typeof MyEventsRoute
  MyTicketsRoute: typeof MyTicketsRoute
  PrivacyRoute: typeof PrivacyRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  EventsSlugRoute: typeof EventsSlugRoute
  HostNewRoute: typeof HostNewRoute
  HostsSlugRoute: typeof HostsSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  HostSlugDashboardRoute: typeof HostSlugDashboardRoute
  HostSlugMembersRoute: typeof HostSlugMembersRoute
  HostSlugReportsRoute: typeof HostSlugReportsRoute
  HostSlugEventsNewRoute: typeof HostSlugEventsNewRoute
  HostSlugEventsEventIdCheckInRoute: typeof HostSlugEventsEventIdCheckInRoute
  HostSlugEventsEventIdEditRoute: typeof HostSlugEventsEventIdEditRoute
  HostSlugEventsEventIdGalleryRoute: typeof HostSlugEventsEventIdGalleryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tickets': {
      id: '/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof MyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$slug': {
      id: '/hosts/$slug'
      path: '/hosts/$slug'
      fullPath: '/hosts/$slug'
      preLoaderRoute: typeof HostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/new': {
      id: '/host/new'
      path: '/host/new'
      fullPath: '/host/new'
      preLoaderRoute: typeof HostNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/reports': {
      id: '/host/$slug/reports'
      path: '/host/$slug/reports'
      fullPath: '/host/$slug/reports'
      preLoaderRoute: typeof HostSlugReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/members': {
      id: '/host/$slug/members'
      path: '/host/$slug/members'
      fullPath: '/host/$slug/members'
      preLoaderRoute: typeof HostSlugMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/dashboard': {
      id: '/host/$slug/dashboard'
      path: '/host/$slug/dashboard'
      fullPath: '/host/$slug/dashboard'
      preLoaderRoute: typeof HostSlugDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/events/new': {
      id: '/host/$slug/events/new'
      path: '/host/$slug/events/new'
      fullPath: '/host/$slug/events/new'
      preLoaderRoute: typeof HostSlugEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/events/$eventId/gallery': {
      id: '/host/$slug/events/$eventId/gallery'
      path: '/host/$slug/events/$eventId/gallery'
      fullPath: '/host/$slug/events/$eventId/gallery'
      preLoaderRoute: typeof HostSlugEventsEventIdGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/events/$eventId/edit': {
      id: '/host/$slug/events/$eventId/edit'
      path: '/host/$slug/events/$eventId/edit'
      fullPath: '/host/$slug/events/$eventId/edit'
      preLoaderRoute: typeof HostSlugEventsEventIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$slug/events/$eventId/check-in': {
      id: '/host/$slug/events/$eventId/check-in'
      path: '/host/$slug/events/$eventId/check-in'
      fullPath: '/host/$slug/events/$eventId/check-in'
      preLoaderRoute: typeof HostSlugEventsEventIdCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExploreRoute: ExploreRoute,
  MyEventsRoute: MyEventsRoute,
  MyTicketsRoute: MyTicketsRoute,
  PrivacyRoute: PrivacyRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  EventsSlugRoute: EventsSlugRoute,
  HostNewRoute: HostNewRoute,
  HostsSlugRoute: HostsSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  HostSlugDashboardRoute: HostSlugDashboardRoute,
  HostSlugMembersRoute: HostSlugMembersRoute,
  HostSlugReportsRoute: HostSlugReportsRoute,
  HostSlugEventsNewRoute: HostSlugEventsNewRoute,
  HostSlugEventsEventIdCheckInRoute: HostSlugEventsEventIdCheckInRoute,
  HostSlugEventsEventIdEditRoute: HostSlugEventsEventIdEditRoute,
  HostSlugEventsEventIdGalleryRoute: HostSlugEventsEventIdGalleryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
